# SwiftLint Configuration for Nuvie

# Paths to include in linting
included:
  - Nuvie
  - ios

# Paths to exclude from linting
excluded:
  - Pods
  - Carthage
  - DerivedData
  - build
  - .build
  - Package.swift
  - "*/Generated/*"

# Enabled rules
opt_in_rules:
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace
  - line_length

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - db
    - x
    - y
    - i
    - j
    - k

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  # Warn about print statements in production code
  no_print_in_production:
    regex: '^\s*print\s*\('
    message: "Consider using a logging framework instead of print()"
    severity: warning
    match_kinds:
      - identifier

  # Enforce TODO format
  todo_format:
    regex: '//\s*TODO(?!:)'
    message: "TODO comments should be formatted as // TODO: description"
    severity: warning

# Reporter type
reporter: "xcode"
